[package]
name = "rswasm-icongen"
version = "0.1.0"
edition = "2024"
authors = ["aoaochan"]

[lib]
crate-type = ["cdylib"]

[dependencies]
console_error_panic_hook = "0.1.7"
icns = "0.3.1"
ico = "0.4.0"
image = "0.25.6"
imageproc = "0.25.0"
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"