name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Cache wasm-pack
      uses: actions/cache@v3
      with:
        path: ~/.wasm-pack
        key: ${{ runner.os }}-wasm-pack

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build
      run: |
        rm -rf ./pkg
        rm -rf ./www/pkg
        wasm-pack build --target web
        rm -f ./pkg/README.md
        mv ./pkg ./www/

    - name: Remove .gitignore from pkg
      run: rm -f www/pkg/.gitignore

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Deploy to Repository
      run: |
        cd www
        git init
        git add .
        git commit -m "Deploy from GitHub Actions"
        git branch -M main
        git remote add origin https://x-access-token:${SECRET_TOKEN}@github.com/aoaochan/pngicoicns-gen.io.git
        git push -f origin main
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }} 