name: Build and Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust & wasm-pack
      run: |
        rustup target add wasm32-unknown-unknown
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build WASM (pkg/)
      run: |
        wasm-pack build --target web
        rm -f pkg/README.md

    - name: Add pkg to tag commit
      run: |
        git config user.name  "github-actions"
        git config user.email "actions@github.com"
        git add -f pkg
        if ! git diff --cached --quiet; then
          git commit -m "Add pkg artifacts"
          git push --force origin HEAD:${{ github.ref }}
        else
          echo "No changes in pkg - skip commit"
        fi
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

    - name: Upload pkg to Release
      uses: softprops/action-gh-release@v1
      with:
        files: pkg/**/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push www/ to pages repo
      env:
        SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}  # PAT (repo 권한)
      run: |
        rm -rf www/pkg && cp -r pkg www/pkg
        cd www
        git init -b main
        git config user.name  "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy for ${{ github.ref_name }}"
        git remote add origin https://x-access-token:${SECRET_TOKEN}@github.com/aoaochan/pngicoicns-gen.io.git
        git push -f origin main